// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_tabs: dynamic(() => import("./AboutTabs")),
  about_us_section: dynamic(() => import("./AboutUsSection")),
  acknowledgements_section: dynamic(() => import("./AcknowledgementsSection")),
  apply_section: dynamic(() => import("./ApplySection")),
  call_to_action: dynamic(() => import("./CallToAction")),
  contact_us_section: dynamic(() => import("./ContactUsSection")),
  job_details_section: dynamic(() => import("./JobDetailsSection")),
  map: dynamic(() => import("./Map")),
  our_values_section: dynamic(() => import("./OurValuesSection")),
  portfolio_section: dynamic(() => import("./PortfolioSection")),
  request_offer_section: dynamic(() => import("./RequestOfferSection")),
  reviews_section: dynamic(() => import("./ReviewsSection")),
  separator: dynamic(() => import("./Separator")),
  services_and_products_section: dynamic(
    () => import("./ServicesAndProductsSection"),
  ),
  site_banner: dynamic(() => import("./SiteBanner")),
  text_section: dynamic(() => import("./TextSection")),
  we_are_hiring_section: dynamic(() => import("./WeAreHiringSection")),
  what_we_do_section: dynamic(() => import("./WhatWeDoSection")),
};
