// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_us_section: dynamic(() => import("./AboutUsSection")),
  reviews_section: dynamic(() => import("./ReviewsSection")),
  site_banner: dynamic(() => import("./SiteBanner")),
  what_we_do_section: dynamic(() => import("./WhatWeDoSection")),
};
